outpath: emotionsets
seeds: [42,892,234,2389]
img-models: []
  #- sd 
  #- dalle

#used for stable diffusion and dalle
img-templates:
  - a {contexts} expressing the emotion {emotions}
  - a {contexts} expressing {emotions}
  - a {contexts} feeling {emotions}

text-models:
  - gpt3

#used if gpt3 is enabled in models
text-templates:
  - 'Write a story about a {contexts} expressing the emotion {emotions}:'

contexts:
  - robot
  - person

emotions: 
  - amusement
  - affection
  - positive Surprise
  - satisfaction
  - gratitude
  - annoyance
  - hate
  - shock
  - dissatisfaction
  - resentment
