outpath: emotionsets
seeds: [42,892,234,2389]

# currently sd and dalle are supported
img-models:
  - sd 
  - dalle

# used by image models
img-templates:
  - a {contexts} expressing the emotion {emotions}
  - a {contexts} expressing {emotions}
  - a {contexts} feeling {emotions}

# currently only gpt3 is supported
text-models:
  - gpt3

# used by text-models
text-templates:
  - 'Write a story about a {contexts} expressing the emotion {emotions}:'

# custom tokens
contexts:
  - robot
  - person

emotions: 
  - amusement
  - affection
  - positive Surprise
  - satisfaction
  - gratitude
  - annoyance
  - hate
  - shock
  - dissatisfaction
  - resentment
