outpath: emotionsets
seeds: [42,892,234,2389]
models:
  - sd 
  - dalle

templates:
  - a {contexts} expressing the emotion {emotions}
  - a {contexts} expressing {emotions}
  - a {contexts} feeling {emotions}

contexts:
  - robot
  - person

emotions: 
  - amusement
  - affection
  - positive Surprise
  - satisfaction
  - gratitude
  - annoyance
  - hate
  - shock
  - dissatisfaction
  - resentment
